"""Build the static sample-report site published to GitHub Pages.

For every real example log under `examples/`, runs it through
trainspotter's own library code -- the same `load_run` / `run_all` /
`render_html` the CLI calls, not a re-implementation -- and writes its
HTML report. The index page's finding counts are computed from those same
results at build time; nothing here is hand-typed or copied from a
previous run, so the site can never drift from what the tool actually
reports.

Usage:
    uv run python scripts/build_site.py [--out-dir site]

Output: `<out-dir>/index.html` plus one `<out-dir>/<example>.html` per
example (default out-dir: `site/`, gitignored -- CI builds and publishes
it fresh on every push; see .github/workflows/pages.yml).
"""

from __future__ import annotations

import argparse
import html
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from trainspotter.detectors import Finding, run_all
from trainspotter.readers import load_run
from trainspotter.report import render_html

REPO_ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = REPO_ROOT / "examples"


@dataclass(frozen=True)
class ExampleMeta:
    slug: str
    title: str
    blurb: str


# Titles and one-line blurbs are static labels, same spirit as a table
# caption; the finding counts shown next to each one are never hand-typed
# (see main()) -- only what a fresh `run_all()` reports at build time.
EXAMPLES = [
    ExampleMeta(
        "baseline",
        "Baseline",
        "Ordinary warmup + cosine-decay training on the full dataset. Nothing wrong with it.",
    ),
    ExampleMeta(
        "divergence",
        "Divergence",
        "320 healthy steps, then a simulated LR-schedule incident blows the run up.",
    ),
    ExampleMeta(
        "overfitting",
        "Overfitting",
        "40 training examples, no regularization -- eval loss turns upward after step 125.",
    ),
    ExampleMeta(
        "missing_warmup",
        "Missing warmup",
        "Learning rate jumps straight to its peak from step 0, no ramp-up.",
    ),
    ExampleMeta(
        "throughput_drop",
        "Throughput drop",
        "A real, measured mid-run slowdown (an actual time.sleep, not a fabricated number).",
    ),
    ExampleMeta(
        "transformers_tinygpt2",
        "Real transformers.Trainer run",
        "A genuine 2-layer GPT-2 trained via transformers.Trainer, not the numpy MLP.",
    ),
]


def _counts(findings: list[Finding]) -> dict[str, int]:
    counts = {"error": 0, "warning": 0, "info": 0}
    for f in findings:
        counts[f.severity] += 1
    return counts


def build_index(rows: list[tuple[ExampleMeta, dict[str, int]]], generated: str) -> str:
    cards = []
    for meta, counts in rows:
        chips = "".join(
            f'<span class="chip sev-{sev}">{counts[sev]} {sev}</span>' for sev in ("error", "warning", "info")
        )
        cards.append(
            f"""<a class="card" href="{html.escape(meta.slug)}.html">
  <h2>{html.escape(meta.title)}</h2>
  <p>{html.escape(meta.blurb)}</p>
  <div class="chips">{chips}</div>
</a>"""
        )
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>trainspotter -- sample reports</title>
<style>{_CSS}</style>
</head>
<body>
<div class="wrap">
  <header>
    <span class="brand-mark" aria-hidden="true">&#9679;</span>
    <h1>TRAINSPOTTER</h1>
    <p class="sub">Sample HTML reports, generated by the CLI against the real example
    logs committed in <code>examples/</code>. Finding counts below are computed fresh
    at each build, not hand-typed.</p>
  </header>
  <main class="grid">
    {"".join(cards)}
  </main>
  <footer>
    <span>Built {html.escape(generated)} &middot;
    <a href="https://github.com/antonsoo/trainspotter">source</a></span>
  </footer>
</div>
</body>
</html>
"""


_CSS = """
:root {
  --bg: #0a0d10; --panel: #10151a; --line: #1f2830; --line-strong: #2c3944;
  --text: #d9e2e8; --text-muted: #8b97a1; --text-dim: #57626b;
  --err: #ff5d5d; --warn: #f2b84b; --info: #5fb3ff;
  --mono: ui-monospace, "SFMono-Regular", "Cascadia Mono", Consolas, monospace;
  --sans: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
}
* { box-sizing: border-box; }
html, body { margin: 0; background: var(--bg); color: var(--text); }
body { font-family: var(--sans); font-size: 15px; line-height: 1.5; }
.wrap { max-width: 900px; margin: 0 auto; padding: 40px 20px 60px; }
header { border-bottom: 1px solid var(--line-strong); padding-bottom: 20px; margin-bottom: 28px; }
.brand-mark { color: var(--info); font-size: 12px; }
h1 { font-family: var(--mono); font-size: 22px; letter-spacing: 0.12em; display: inline; margin-left: 8px; }
.sub { color: var(--text-muted); max-width: 640px; margin-top: 14px; }
.sub code { font-family: var(--mono); color: var(--text); }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 14px; }
.card {
  display: block; background: var(--panel); border: 1px solid var(--line);
  border-radius: 4px; padding: 18px; text-decoration: none; color: inherit;
  transition: border-color 0.15s ease;
}
.card:hover { border-color: var(--info); }
.card h2 { font-size: 16px; margin: 0 0 8px; color: var(--text); }
.card p { font-size: 13px; color: var(--text-muted); margin: 0 0 14px; min-height: 34px; }
.chips { display: flex; gap: 8px; font-family: var(--mono); font-size: 11px; }
.chip { padding: 2px 7px; border-radius: 2px; border: 1px solid currentColor; }
.chip.sev-error { color: var(--err); }
.chip.sev-warning { color: var(--warn); }
.chip.sev-info { color: var(--info); }
footer { margin-top: 36px; padding-top: 16px; border-top: 1px solid var(--line);
  color: var(--text-dim); font-family: var(--mono); font-size: 11px; }
footer a { color: var(--text-dim); }
@media (max-width: 480px) { .grid { grid-template-columns: 1fr; } }
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default="site", help="Output directory (default: site)")
    args = parser.parse_args()

    out_dir = REPO_ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: list[tuple[ExampleMeta, dict[str, int]]] = []
    for meta in EXAMPLES:
        src = EXAMPLES_DIR / f"{meta.slug}.trainer_state.json"
        run = load_run(src)
        findings = run_all(run)
        page = render_html(run, findings, title=f"trainspotter - {meta.title}")
        (out_dir / f"{meta.slug}.html").write_text(page, encoding="utf-8")
        rows.append((meta, _counts(findings)))
        print(f"  {meta.slug}: {_counts(findings)}")

    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    (out_dir / "index.html").write_text(build_index(rows, generated), encoding="utf-8")
    print(f"wrote {out_dir}/index.html and {len(rows)} report(s)")


if __name__ == "__main__":
    main()
